#!/bin/bash

declare     SOURCE_BASE
declare -a  SOURCE
declare -a  TARGET

SOURCE_BASE="webtest:/var/www/test/contao31"
SOURCE[0]="system/modules/db-file-inserttag"
TARGET[0]="modules/db-file-inserttag"


function mountTarget()
{
  source="${SOURCE_BASE}/${1}"
  target="$2"

  mount | grep "${source}" > /dev/null
  ismount=$?

  if [[ $ismount -ne 0 ]]; then
    sshfs "${source}" "$target"
  fi
}



function umountTarget()
{
  source="${SOURCE_BASE}/${1}"
  target="$2"

  mount | grep "$source" > /dev/null
  ismount=$?

  if [[ $ismount -eq 0 ]]; then
    fusermount -u "$target"
  fi
}



if [[ "$1" == "-u" ]]; then
  for (( i=0; i<${#SOURCE[*]}; ++i))
  {
    umountTarget "${SOURCE[$i]}" "${TARGET[$i]}"
  }
else
  for (( i=0; i<${#SOURCE[*]}; ++i))
  {
    mountTarget "${SOURCE[$i]}" "${TARGET[$i]}"
  }
fi
